# Generated by Django 5.0.7 on 2024-08-01 17:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('url', models.CharField(max_length=255, null=True)),
                ('type', models.CharField(choices=[('PHYSIC', 'PHYSIC'), ('DIGITAL', 'DIGITAL'), ('BOTH', 'BOTH')])),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
