# Generated by Django 5.0.7 on 2024-08-01 19:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('image_preview', models.CharField(max_length=255, null=True)),
                ('type', models.CharField(choices=[('PHYSIC', 'PHYSIC'), ('DIGITAL', 'DIGITAL'), ('BOTH', 'BOTH')])),
                ('state', models.CharField(choices=[('IN_STOCK', 'IN_STOCK'), ('REFILLING', 'REFELLING'), ('SOULD_OUT', 'SOULD_OUT')])),
                ('base_pricing', models.FloatField(default=0.0)),
                ('base_cost', models.FloatField(null=True)),
                ('in_existence', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
