# Generated by Django 5.0.7 on 2024-08-03 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='state',
            field=models.CharField(choices=[('IN_STOCK', 'IN_STOCK'), ('REFILLING', 'REFILLING'), ('SOULD_OUT', 'SOULD_OUT')]),
        ),
    ]
