# Generated by Django 5.0.7 on 2024-08-05 08:09

from django.db import migrations
from product.models import AlertProduct


def create_alert_defalt(apps, schema_editor):
    AlertProduct.objects.create(
        min_quantity=10,
        is_default=True,
        is_active=True
    )

class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alertproduct'),
    ]

    operations = [
        migrations.RunPython(create_alert_defalt),
    ]
