# Generated by Django 5.0.7 on 2024-07-31 01:56

from django.db import migrations
from django.contrib.auth import get_user_model


def create_user_defalt(apps, schema_editor):
    User = get_user_model()
    SUPERUSER_USERNAME = 'admin'
    SUPERUSER_EMAIL = 'admin@exitosa.com'
    SUPERUSER_PASSWORD = 'Exitosa1234'
    
    if not User.objects.filter(email=SUPERUSER_EMAIL).exists():
        User.objects.create_superuser(
            first_name=SUPERUSER_USERNAME,
            email=SUPERUSER_EMAIL,
            password=SUPERUSER_PASSWORD
        )

class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_user_defalt),
    ]

